### ISSUE TITLE
Redesign Hero Section

### ISSUE THREAD

**Issue by ajaynegi45** [ajaynegi45/LibraryMan#4]

**Comment by Sky-De** [comment]
@ajaynegi45 hi, please assign this to me, i will fix this as soon as i receive assignment
Thanks

**Comment by ajaynegi45** [comment]
**Assignee:** @Sky-De 

Hi @Sky-De ,

Thank you for your willingness to work on the "Redesign Hero Section" issue. I've just assigned the issue to you. You can now proceed with the task, and we look forward to seeing your improvements. If you have any questions or need further assistance during the process, please feel free to ask.

**Comment by Sky-De** [comment]
@ajaynegi45 hi again, this issue is resolved, actually I just commented out the Hero component of the code and redesigned the search section, because it was better UX and UI practice to use this section rather than the Hero section, 
as a result, it is ready with a great look with the minimum amount of code or structure change
I hope you like it
## Gifs BEFORE and AFTER for showcases

**DESKTOP--before**

![before-d-min](https://github.com/ajaynegi45/Library/assets/79264045/292532b7-0ecd-4e09-8e53-ccc00d240774)


**DESKTOP--after**

![after-d-min](https://github.com/ajaynegi45/Library/assets/79264045/9236ce70-56bd-4250-826c-d9d85f38ce77)



********************************************************************************************************************************************
**MOBILE--before**

![before-m-min](https://github.com/ajaynegi45/Library/assets/79264045/bb8db849-04cd-4661-b620-a0bd04d2972a)


**MOBILE--after**

![after-m-min](https://github.com/ajaynegi45/Library/assets/79264045/9e8d256e-e0dc-4aa0-8e53-d616bd867140)




 If you have any questions , feel free to ask, otherwise let me know to create a PR for this issue
 thanks

**Comment by ajaynegi45** [comment]
I don't want this  hero section. I want Complete change

ex:- 
<img width="849" alt="Screenshot 2023-10-02 at 1 07 56 AM" src="https://github.com/ajaynegi45/Library/assets/97536703/b33bef1e-a004-4c07-84dc-3e6665b37a05">

**Comment by Sky-De** [comment]
@ajaynegi45 thanks for your response
There is some points that i like to made here 

1. I believe search-book component which I've redesign is much more appealing than design you provided in term of user attraction, i highly recommend you to keep design same as i provided

2. If you really wish change this then i have some questions about do you want to keep search-book component and then add this design as Hero section?
Also you've used Hindi for title which i can't extract from PNG and i don't know what is that (provide that title in text here then i can copy and paste it)
Last thing about image which you've used, does it exist within your image folder?

Last thing i highly recommend you before i change anything let me create PR then you merge it then take a look at it, then if you were not satisfied you can simply let me know and I'll change that to your intended design
Thanks

**Comment by ajaynegi45** [comment]
> @ajaynegi45 thanks for your response There is some points that i like to made here
> 
> 1. I believe search-book component which I've redesign is much more appealing than design you provided in term of user attraction, i highly recommend you to keep design same as i provided
> 2. If you really wish change this then i have some questions about do you want to keep search-book component and then add this design as Hero section?
>    Also you've used Hindi for title which i can't extract from PNG and i don't know what is that (provide that title in text here then i can copy and paste it)
>    Last thing about image which you've used, does it exist within your image folder?
> 
> Last thing i highly recommend you before i change anything let me create PR then you merge it and take a look at it as live project, after that if you were not satisfied you can simply let me know and I'll change that to your desired design Thanks

Create pr I will check.


https://github.com/ajaynegi45/Library/issues/4#issuecomment-1750174193 This is just for example purpose not for implementation. 


My future plan https://github.com/ajaynegi45/Library/issues/27 and https://github.com/ajaynegi45/Library/issues/1
